name: basic_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.5.3

  # Local database
  drift: ^2.19.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  
  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11

  drift_dev: ^2.19.1
  retrofit_generator: ^8.1.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true


